### ISSUE TITLE
keeping your commits balanced 

### ISSUE THREAD

**Issue by pat-cki** [fac19/week8-DEKN#38]
I understand it might be really hard to keep your commits balanced due to the remote nature of work, but you should definitely pay more attention to it in your future projects. Remember that working as a team is more important than completing a project.

**Comment by oliverjam** [comment]
I think it looks bad because Gio has 9 "co-author" commits, which don't seem to show up in the contributors graphs. The [Pulse](https://github.com/fac19/week8-DEKN/pulse) view shows everyone having about the same total.

It might be worth alternating who the "co-authored by" person is though, since that account seems to get de-prioritised by the GitHub UI

**Comment by glrta** [comment]
I always check the pulse and only noticed today that the contributor's tab shows something different. With the co-authoring, I tend to not worry about what computer we are working on as Live share sometimes can be a pain to set up. Thank you for pointing this out.
